version: 2
project_name: claude-rlm

before:
  hooks:
    - go mod tidy

builds:
  - id: rlm
    main: ./cmd/rlm
    binary: rlm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildTime={{.Date}}
      - -X main.GitCommit={{.ShortCommit}}

archives:
  # Archives with docs for manual download
  - id: archives
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - agents/*
  # Raw binaries for auto-updater
  - id: binaries
    format: binary
    name_template: >-
      rlm_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: Kukks
    name: claude-rlm
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"
